팝업 뷰 관련 작업
ILGOB/NANO pull request #11
Opened 2024-03-19 08:29 UTC by blooper20

- 보관함 테이블 뷰 editingMode로 변경 가능
- SearchViewController에서 테이블 row을 탭했을 때 팝업 창이 뜨고 dismiss하는 버튼 구현
- 팝업에서 팝업으로 이동하는 로직 구현
- 팝업뷰의 Bool 값으로  네비게이션을 설정

2024-03-20 05:42 UTC, woin2ee requested changes

2024-03-20 05:42 UTC, woin2ee commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        }).disposed(by: disposebag)
혹시 `PopUpViewController` 가 dismiss 될 때 메모리 해제가 안되는 이슈가 있는지 테스트 해보셨나요? 아마 이 부분 때문에 이슈가 있을것으로 예상됩니다.
만약 이슈가 있다면 `[weak self]` or `subscribe(with:onNext:)` 사용으로 해결할 수 있습니다.

2024-03-20 05:42 UTC, woin2ee commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        if navigation {
혹시 여기서 `navigation` Bool 변수가 뭘 의미하는지 모호해 보이지 않나요?
의미에 따라 `is`, `has` 등의 단어를 추가하여 의미를 분명하게 만듦으로써 코드 품질을 향상시킬 수 있습니다!
"if `  ` navigation ~~" 을 영어 문장이라고 생각하고 가장 자연스럽게 읽히는 단어를 찾는것도 좋은 방법입니다.
https://soojin.ro/blog/naming-boolean-variables <- 이 포스트 강추

2024-03-20 05:42 UTC, woin2ee commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        self.popupView.layoutSubviews()
Docs 에서 `layoutSubviews()` 함수의 Discussion 문단 마지막을 보면 

> You should not call this method directly.

로 시작하는 내용이 있습니다. 한 번 읽어보고 코드를 적절하게 수정하면 될 것 같습니다~

2024-03-20 05:42 UTC, woin2ee commented on NANO/Presentation/ViewControllers/SearchViewController.swift
> +            fatalError("snapshot 오류")
어떤 이유로 인해 Snapshot 을 가져오는데 실패할 경우 앱이 강제 종료되는것보다 나은 대처 방안이 있지 않을까요?

2024-03-20 05:42 UTC, woin2ee commented on NANO/Presentation/Views/PopUp/SubViews/PlaylistSelectView.swift
> +        }).disposed(by: disposebag)
이 부분도 아직 구현은 안됐지만 순환 참조를 신경 써주세요~

2024-03-20 05:42 UTC, woin2ee commented on NANO/Presentation/Views/PopUp/SubViews/SongDetailInfoView.swift
> +        }).disposed(by: disposebag)
`SongDetailInfoView` 에 대해서도 메모리 해제가 안되는 이슈가 있다면 원인이 이 부분일 것으로 예상됩니다.

2024-03-20 11:39 UTC, blooper20 commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        self.popupView.layoutSubviews()
전에도 얘기 했던거 같았는데 잊고 있었네요 ㅠㅜ

2024-03-20 11:39 UTC, blooper20 commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        if navigation {
예전에 읽었었던 내용인데 뭔가 네이밍 할때 찜찜한 이유가 이거였군요

2024-03-20 12:18 UTC, blooper20 commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        }).disposed(by: disposebag)
메모리 해제를 확인 하는 방법 중에서 Instrumnets 의 leak을 활용하는 방법으로 테스트를 해봤는데
검색한대로는 알아낼수 없지만 밑에 영상처럼 위의 Allocations 그래프에서 두번째 뷰에서 첫번째 뷰로 넘어갈 때엔 그래프가 감소하는게 있었는데 팝업 창이 뜨고 dismiss 될 때엔 그래프가 감소하지 않는 걸 발견 했는데 이를 통해서 메모리 해제가 안된다는걸 알수있는 건지 궁금합니다.

https://github.com/ILGOB/NANO/assets/70786167/d307babb-a6a3-41e5-ba7a-099281db2e14

2024-03-20 12:19 UTC, blooper20 commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        }).disposed(by: disposebag)
<img width="781" alt="스크린샷 2024-03-20 오후 9 19 17" src="https://github.com/ILGOB/NANO/assets/70786167/1f155ba1-90ec-495f-af3a-11270d1abe7c">
뭔가 조금 더 검색해보니 이런식으로 쌓이기만 하고 해제는 안된 모습을 찾은거 같습니다
이게 맞는지는 모르겠습니다만

2024-03-20 12:46 UTC, blooper20 commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        }).disposed(by: disposebag)
`[weak self]` 로 메모리 누수가 생기는 걸 방지하는건 해봤는데
`subscribe(with:onNext:)` 이 부분은 어떤 방식으로 해결해야 하는 지 잘 모르겠습니다

2024-03-20 14:54 UTC, woin2ee commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        }).disposed(by: disposebag)
일단 현재 메모리 해제가 안되는 이슈가 있다면 정확히는 `Memory leak` 이 아니라 `Abandoned memory` 일 가능성이 높습니다.
Memory leak 은 단순히 `A <-> B` 으로 표현되지만 Abandoned memory 는 어딘가에 참조가 계속 존재하지만 로직 상 더는 접근할 수 없게된 메모리를 의미합니다. (https://stackoverflow.com/questions/8840168/whats-the-difference-between-abandoned-memory-and-a-memory-leak, https://help.apple.com/instruments/mac/current/#/dev7b8f6eb6 마지막 문단 참조)
여기서는 '`Abandoned memory` 라는게 있다' 정도만 알아도 될 것 같구 이 다름으로 인해 Instruments 툴의 Leak 메뉴로는 잡히지 않는다는걸 이해하면 충분할 것 같습니다.

Allocations 그래프를 이용해서 실제로 쌓이는 메모리를 확인한 것은 👍👍👍 제대로 확인한 것 같습니다.
다른 방식으로 확인하는 법을 알려드리자면,
<img width="808" alt="image" src="https://github.com/ILGOB/NANO/assets/81426024/f747694a-365d-4573-bcdb-3a47cd7dac0d">
위 사진처럼 ViewController 또는 클래스 이름으로 검색하면 필터링된 결과를 볼 수 있습니다.
여기서 `Persistent` 와 `Transient` 가 중요한데, `Persistent` 는 현재 실제로 메모리에 존재하는 갯수를 의미하고 `Transient` 는 할당되었다가 해제된 횟수를 의미합니다.
위 예시 사진을 분석하자면 `GeneralSettingsCoordinator` 와 `ThemeSettingCoordinator` 는 5번은 정상적으로 메모리가 해제 됐지만 3번(또는 2번: 현재 화면일경우)은 어떤 올바르지 않은 방법을 통해 정상적으로 메모리가 해제되지 않았다는걸 의미합니다.
또는 Xcode 에서 앱을 실행했을 때 <img width="27" alt="image" src="https://github.com/ILGOB/NANO/assets/81426024/8b9b109a-2377-43be-b96d-f7e50ab13b41"> 아이콘을 누르면 나오는 메모리 그래프를 이용하여 
<img width="303" alt="image" src="https://github.com/ILGOB/NANO/assets/81426024/fdc5e914-dc07-44ed-b1fb-be7965b9f75c">
해제되지 않고 남아있는 인스턴스들을 확인 가능합니다. 이 메모리 그래프에서는
<img width="586" alt="image" src="https://github.com/ILGOB/NANO/assets/81426024/67548687-5bbb-4211-a9d9-cfe57eb79ffd">
위 사진 처럼 어떤 객체가 꼬리에 꼬리를 물고 해제되지 못하게 참조하고 있는지 확인할 수도 있습니다.

`subscribe(with:onNext:)` 함수는 현재 사용하고 있는 `subscribe(onNext:)` 대신 사용할 수 있는 함수인데 `with` 파라미터에 어떤 객체를 넘기면 내부적으로 해당 객체를 약한 참조로 사용하는 편의 함수입니다.

사용예)
```swift
popupView.dismissButton.rx.tap
  .subscribe(with: self, onNext: { owner, _ in
    owner.dismiss(animated: true)
  })
  .disposed(by: disposebag)
```

2024-03-20 15:02 UTC, woin2ee commented on NANO/Presentation/ViewControllers/PopUpViewController.swift
> +        }).disposed(by: disposebag)
> Allocations 그래프에서 두번째 뷰에서 첫번째 뷰로 넘어갈 때엔 그래프가 감소하는게 있었는데 팝업 창이 뜨고 dismiss 될 때엔 그래프가 감소하지 않는 걸 발견 했는데 이를 통해서 메모리 해제가 안된다는걸 알수있는 건지 궁금합니다.

이 질문에 대한 답변은: 그래프의 상승이 전체적인 메모리 할당량의 증가를 의미하고 그래프의 하락이 감소를 의미하므로 이론적으로는 이를 통해서 메모리 해제가 정상적으로 이루어지지 않고 있다는 걸 알 수 있습니다. 하지만 개인적인 경험으로는 메모리 해제가 정상적으로 이루어짐에도 다른 요인 때문인 건지 그래프가 계속 상승하는 걸 겪어봐서 확신할 순 없다고 생각합니다. 이 부분은 더 지식이 필요하고 정확한 테스트가 필요합니다.

2024-03-21 10:12 UTC, blooper20 commented on NANO/Presentation/ViewControllers/SearchViewController.swift
> +            fatalError("snapshot 오류")
빈 UIView라도 반환 하게 끔 하려했는데 생각처럼 되지 않아 우선 fatalError로 작동하게끔 한거긴 하지만 뾰족한 수가 안떠오릅니다 ㅠㅜ

2024-03-22 10:25 UTC, woin2ee commented on NANO/Presentation/ViewControllers/SearchViewController.swift
> +            fatalError("snapshot 오류")
가장 좋은 방법은 스냅샷을 가져오는데 실패하는 케이스가 뭐가 있는지 확인하고 적절한 대처를 하는건데 생각보다 정보가 없네요.
사용자가 재시도하게끔 해당 시도를 무시하는것도 하나의 방법일듯 합니다.

2024-03-26 06:54 UTC, merged