커스텀 탭바 완성 후 rootViewController를 ChoiceViewController로 설정 후 연결
ILGOB/NANO pull request #9
Opened 2024-03-06 10:18 UTC by blooper20

#### 커밋 내용
- TabBar에 각 뷰 컨트롤러 연결
- rootVC를 ChoiceVC로 설정
#### 미완
- [ ] 네비게이션 타이틀이 화면에 맞지않게 설정
- [ ] 노래방 브랜드를 선택했을 때 스태틱 변수에 저장 되게끔 설정
- [ ] 테이블의 row를 탭 했을 때 알맞은 팝업이 뜨게끔 설정

2024-03-06 17:08 UTC, woin2ee requested changes

2024-03-06 17:08 UTC, woin2ee commented on NANO/Presentation/ViewControllers/SearchViewController.swift
> +        navigationController?.navigationBar.topItem?.title = ""
`viewWillAppear(_:)` 의 Documentation 에 보면
> If you override this method, you must call super at some point in your implementation.

어느 부분에서 super.viewWillAppear() 를 호출해야한다고 써있습니다!

2024-03-06 17:08 UTC, woin2ee commented on NANO/Presentation/ViewControllers/SearchViewController.swift
> +        navigationController?.navigationBar.topItem?.title = ""
+ navigationController 의 `topItem` 에는 `navigationItem` 프로퍼티로 바로 접근할 수도 있습니당

2024-03-06 17:08 UTC, woin2ee commented on NANO/Presentation/ViewControllers/ReleaseViewController.swift
> +        navigationController?.navigationBar.topItem?.title = ""
super 를 호출해야 합니다.(위와 동일)

2024-03-06 17:08 UTC, woin2ee commented on NANO/Presentation/ViewControllers/MySongsViewController.swift
> +        navigationController?.navigationBar.topItem?.title = "보관함"
super 를 호출해야 합니다.(위와 동일)

2024-03-06 17:08 UTC, woin2ee commented on NANO/Presentation/ViewControllers/ChoiceViewController.swift
> +        let customTabBarController = CustomTabBarController()
버튼 액션에서 TabBarController 를 생성하는게 일반적이진 않아보이는데 `ChoiceViewController` 와 `onlyTitleButton` 이 어떤 화면에서 어떤 역할을 하는지 추가 설명이 가능할까요? 사진도 있으면 더 좋습니다~

2024-03-07 03:54 UTC, blooper20 commented on NANO/Presentation/ViewControllers/ChoiceViewController.swift
> +        let customTabBarController = CustomTabBarController()
<img width="399" alt="스크린샷 2024-03-07 오후 12 49 16" src="https://github.com/ILGOB/NANO/assets/70786167/e6978bb3-5433-4162-967d-2cde0a0edb0e">

빨간색 네모친 부분의 버튼이고 버튼을 탭했을 때 스태틱 변수에 브랜드의 이름이 string형으로 저장 되고 
<img width="391" alt="스크린샷 2024-03-07 오후 12 53 17" src="https://github.com/ILGOB/NANO/assets/70786167/1aa13dff-a631-4b2d-ba83-5f2def925e39">

위의 화면인 TabBarController로 화면 전환됩니다

2024-03-07 03:55 UTC, blooper20 commented on NANO/Presentation/ViewControllers/SearchViewController.swift
> +        navigationController?.navigationBar.topItem?.title = ""
자동완성으로 메서드를 만들어서 당연히 포함되어있는줄 알았습니다...

2024-03-07 16:01 UTC, woin2ee approved these changes

2024-03-07 16:01 UTC, woin2ee commented on NANO/Presentation/ViewControllers/ChoiceViewController.swift
> +        let customTabBarController = CustomTabBarController()
아하 이런 흐름이였군뇨 이해했습니다 :)

2024-03-07 16:03 UTC, woin2ee commented on NANO/Presentation/ViewControllers/ChoiceViewController.swift
> +        let customTabBarController = CustomTabBarController()
아하 이런 흐름이였군뇨 이해했습니다 :)

2024-03-12 06:42 UTC, merged